apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: test-api
 name: test-api
spec:
 replicas: 2
 selector:
   matchLabels:
     app: test-api
     ver: v1.0
 template:
   metadata:
     labels:
       app: test-api
       ver: v1.0
   spec:
     containers:
     - image: PUT-TEST-API-IMAGE-URL-HERE
       name: test-api
       ports:
       - containerPort: 8082
       resources:
          limits:
            memory: "100Mi"
            cpu: "100m"